SET SERVEROUTPUT ON;
DECLARE 
  c_gst CONSTANT NUMBER:=18; 
  v_plan NUMBER:=199; 
  v_gst NUMBER; 
  v_total NUMBER;
BEGIN 
  v_gst:=v_plan*c_gst/100; 
  v_total:=v_plan+v_gst; 
  DBMS_OUTPUT.PUT_LINE(RPAD('PLAN',15)||'Jio/Airtel'); 
  DBMS_OUTPUT.PUT_LINE(RPAD('BASE PRICE',15)||TO_CHAR(v_plan,'99,999.99')); 
  DBMS_OUTPUT.PUT_LINE(RPAD('GST @18%',15)||TO_CHAR(v_gst,'99,999.99')); 
  DBMS_OUTPUT.PUT_LINE(RPAD('TOTAL',15)||TO_CHAR(v_total,'99,999.99')); 
  DBMS_OUTPUT.PUT_LINE(RPAD('VALIDITY',15)||TO_CHAR(SYSDATE+28,'DD-MON-YYYY')); 
END;
/